name: 'Hexo Action'
description: 'Hexo CI/CD action for automating deployment.'
author: 'sma11black'
inputs:
  user_name:
    description: 'Github user name'
    required: true
    default: 'github-actions[bot]'
  user_email:
    description: 'Github email'
    required: true
    default: '41898282+github-actions[bot]@users.noreply.github.com'
  deploy_key:
    description: 'The deploy key for Github Pages repo'
    required: true
    default: ''
  commit_msg:
    description: 'Git commit messages to your GitHub Pages repository.'
    required: false
    default: ''
  use_algolia:
    description: 'Use algolia search in your blog'
    required: true
    default: false
outputs:
  notify: # id of output
    description: 'The notification of deployment result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.user_name }}
    - ${{ inputs.user_email }}
    - ${{ inputs.deploy_key }}
    - ${{ inputs.commit_msg }}
    - ${{ inputs.use_algolia }}
branding:
  icon: 'package'  
  color: 'blue'